import type { IpcMain } from 'electron'
import { getDb } from '../database'
import crypto from 'crypto'
import { enqueuSync } from '../services/syncQueue'
import { logAudit } from '../services/auditLog'
import Store from 'electron-store'
import { safeHandle } from './ipcHandler'
import { createNotification } from './notifications'

const store = new Store()

function largePayoutThreshold(): number {
  const saved = (store.get('app_settings') as Record<string, unknown> | undefined) || {}
  return Number(saved.smartbuy_large_payout_threshold ?? 50000) || 50000
}

// Notifies the agent's linked user, if any — a passive (not-yet-linked)
// agent record has nowhere to deliver a notification to.
function notifyAgentUser(db: ReturnType<typeof getDb>, agentId: string | null, type: Parameters<typeof createNotification>[0], title: string, message: string, data?: Record<string, unknown>): void {
  if (!agentId) return
  const agent = db.prepare('SELECT user_id FROM agents WHERE id=?').get(agentId) as { user_id: string | null } | undefined
  if (!agent?.user_id) return
  createNotification(type, title, message, data, { userId: agent.user_id })
}

function authUser(): Record<string, unknown> {
  return (store.get('auth_user') as Record<string, unknown> | undefined) || {}
}

function currentPerms(caller: Record<string, unknown> = authUser()): Record<string, unknown> {
  return ((caller.role as Record<string, unknown>)?.permissions as Record<string, unknown>)
    || (caller.permissions as Record<string, unknown>)
    || {}
}

// Commission rules are company-wide policy — only Super Admin (perms.all)
// may create/edit/delete them, matching the spec's "Admin should control
// everything... No hardcoded logic" and "agents cannot modify commission
// rules." Any caller who can otherwise manage Smart Buy may VIEW rules
// (needed to understand why a ledger line came out the way it did).
function isCommissionAdmin(perms: Record<string, unknown>): boolean {
  return Boolean(perms.all)
}
// Requires an EXPLICIT Smart Buy grant — 'all' or 'chits' — never
// 'customers'. Mirrors the identical fix in chits.ts's canManage() (see the
// SmartBuy fix audit, HIGH-2): the seeded Branch Manager/Cashier roles carry
// customers:true for the ordinary Customers module, and treating that as
// commission-viewing access was an unintended over-grant.
function canViewCommissions(perms: Record<string, unknown>): boolean {
  return Boolean(perms.all || perms.chits)
}
function isGlobalCommissionAccess(perms: Record<string, unknown>): boolean {
  return Boolean(perms.all)
}
function resolveScopedBranchId(perms: Record<string, unknown>, caller: Record<string, unknown>, requested?: unknown): string | undefined {
  if (isGlobalCommissionAccess(perms)) return (requested as string | undefined) || undefined
  return caller.branch_id as string | undefined
}
// For a mutation against an existing ledger line, verifies a non-global
// caller isn't reaching into another branch's commission data.
function assertCommissionBranchScope(perms: Record<string, unknown>, caller: Record<string, unknown>, targetBranchId: unknown): boolean {
  if (isGlobalCommissionAccess(perms)) return true
  return Boolean(targetBranchId) && String(targetBranchId) === String(caller.branch_id || '')
}
function resolveScopedAgentId(caller: Record<string, unknown>): string | null {
  const scope = caller.scope as { level?: string; agentId?: string | null } | undefined
  return scope?.level === 'agent' ? (scope.agentId || null) : null
}
function money(value: number): number {
  return Math.round((Number(value) || 0) * 100) / 100
}

// One structured row per commission status transition — the source of truth
// for the "Generated by System / Approved by Manager / Approved by Admin"
// history the UI shows, distinct from commission_ledger's own columns (which
// only ever reflect the LATEST decision, not the full path there).
async function writeApprovalLog(db: ReturnType<typeof getDb>, params: {
  commissionId: string; agentId?: string | null; branchId?: unknown
  action: string; previousStatus: string | null; newStatus: string
  changedBy: string | null; remarks?: string | null
}): Promise<void> {
  const id = crypto.randomUUID()
  const row = {
    id, commission_id: params.commissionId, agent_id: params.agentId || null,
    branch_id: params.branchId || null, action: params.action,
    previous_status: params.previousStatus, new_status: params.newStatus,
    changed_by: params.changedBy, remarks: params.remarks || null,
  }
  db.prepare(`
    INSERT INTO commission_approval_logs
      (id, commission_id, agent_id, branch_id, action, previous_status, new_status, changed_by, remarks)
    VALUES (@id,@commission_id,@agent_id,@branch_id,@action,@previous_status,@new_status,@changed_by,@remarks)
  `).run(row)
  await enqueuSync('commission_approval_logs', id, 'INSERT', row)
}

const RULE_FIELDS = [
  'name', 'scope', 'scheme_id', 'product_id', 'category_id', 'brand',
  'calculation_type', 'rate', 'ownership_model', 'registration_share_pct', 'sales_share_pct',
  'is_bonus', 'priority', 'active_from', 'active_to', 'status', 'notes',
] as const

export function registerCommissionHandlers(ipcMain: IpcMain) {
  // ── Rules ──────────────────────────────────────────────────────────────
  safeHandle(ipcMain, 'commissions:rules:list', (_e, filters: { schemeId?: string; status?: string } = {}) => {
    const perms = currentPerms()
    if (!canViewCommissions(perms)) return { success: false, error: 'Smart Buy access required' }
    const db = getDb()
    const conditions: string[] = []
    const params: unknown[] = []
    if (filters.schemeId) { conditions.push('(cr.scheme_id = ? OR cr.scope = \'global\')'); params.push(filters.schemeId) }
    if (filters.status) { conditions.push('cr.status = ?'); params.push(filters.status) }
    const where = conditions.length ? `WHERE ${conditions.join(' AND ')}` : ''
    const rows = db.prepare(`
      SELECT cr.*, cs.name as scheme_name, p.name as product_name, c.name as category_name
      FROM commission_rules cr
      LEFT JOIN chit_schemes cs ON cs.id = cr.scheme_id
      LEFT JOIN products p ON p.id = cr.product_id
      LEFT JOIN categories c ON c.id = cr.category_id
      ${where}
      ORDER BY cr.is_bonus, cr.priority DESC, cr.created_at DESC
    `).all(...params)
    return { success: true, data: rows }
  })

  safeHandle(ipcMain, 'commissions:rules:create', async (_e, payload: Record<string, unknown>) => {
    const perms = currentPerms()
    if (!isCommissionAdmin(perms)) return { success: false, error: 'Super Admin access required to create commission rules' }
    const db = getDb()
    const caller = authUser()
    const name = String(payload.name || '').trim()
    if (!name) return { success: false, error: 'Rule name is required' }
    const scope = String(payload.scope || 'global')
    if (!['global', 'scheme', 'product', 'category', 'brand'].includes(scope)) {
      return { success: false, error: 'Invalid rule scope' }
    }
    const calculationType = String(payload.calculation_type || 'percentage')
    const ownershipModel = String(payload.ownership_model || 'registration')
    if (!['registration', 'sales', 'split'].includes(ownershipModel)) {
      return { success: false, error: 'Invalid ownership model' }
    }
    if (ownershipModel === 'split') {
      const reg = Number(payload.registration_share_pct) || 0
      const sales = Number(payload.sales_share_pct) || 0
      if (reg < 0 || sales < 0 || Math.round(reg + sales) !== 100) {
        return { success: false, error: 'Registration + Sales share must both be non-negative and add up to 100%' }
      }
    }
    const rate = Number(payload.rate) || 0
    if (rate < 0) return { success: false, error: 'Rate cannot be negative' }
    if (calculationType === 'percentage' && rate > 100) {
      return { success: false, error: 'A percentage rate cannot exceed 100' }
    }

    const id = crypto.randomUUID()
    const row = {
      id, name, scope,
      scheme_id: scope === 'scheme' ? (payload.scheme_id || null) : null,
      product_id: scope === 'product' ? (payload.product_id || null) : null,
      category_id: scope === 'category' ? (payload.category_id || null) : null,
      brand: scope === 'brand' ? (payload.brand || null) : null,
      calculation_type: calculationType, rate,
      ownership_model: ownershipModel,
      registration_share_pct: ownershipModel === 'split' ? (Number(payload.registration_share_pct) || 0) : 100,
      sales_share_pct: ownershipModel === 'split' ? (Number(payload.sales_share_pct) || 0) : 0,
      is_bonus: payload.is_bonus ? 1 : 0,
      priority: Number(payload.priority) || 0,
      active_from: payload.active_from || null, active_to: payload.active_to || null,
      status: payload.status || 'active', notes: payload.notes || null, created_by: caller.id || null,
    }
    db.prepare(`
      INSERT INTO commission_rules
        (id, name, scope, scheme_id, product_id, category_id, brand, calculation_type, rate,
         ownership_model, registration_share_pct, sales_share_pct, is_bonus, priority,
         active_from, active_to, status, notes, created_by)
      VALUES (@id,@name,@scope,@scheme_id,@product_id,@category_id,@brand,@calculation_type,@rate,
         @ownership_model,@registration_share_pct,@sales_share_pct,@is_bonus,@priority,
         @active_from,@active_to,@status,@notes,@created_by)
    `).run(row)
    await enqueuSync('commission_rules', id, 'INSERT', row)
    logAudit(db, {
      userId: (caller.id as string) || null, action: 'COMMISSION_RULE_CREATED',
      tableName: 'commission_rules', recordId: id, newValues: row,
    })
    return { success: true, data: { id } }
  })

  safeHandle(ipcMain, 'commissions:rules:update', async (_e, id: string, payload: Record<string, unknown>) => {
    const perms = currentPerms()
    if (!isCommissionAdmin(perms)) return { success: false, error: 'Super Admin access required to edit commission rules' }
    const db = getDb()
    const existing = db.prepare(`
      SELECT id, scope, product_id, calculation_type, rate, ownership_model, registration_share_pct, sales_share_pct, created_at
      FROM commission_rules WHERE id=?
    `).get(id) as {
      id: string; scope: string; product_id: string | null; calculation_type: string; rate: number
      ownership_model: string; registration_share_pct: number; sales_share_pct: number; created_at: string
    } | undefined
    if (!existing) return { success: false, error: 'Commission rule not found' }

    const update: Record<string, unknown> = {}
    for (const k of RULE_FIELDS) if (payload[k] !== undefined) update[k] = payload[k]
    if (update.is_bonus !== undefined) update.is_bonus = update.is_bonus ? 1 : 0
    if (update.rate !== undefined) update.rate = Number(update.rate) || 0
    if (update.priority !== undefined) update.priority = Number(update.priority) || 0
    if (update.registration_share_pct !== undefined) update.registration_share_pct = Number(update.registration_share_pct) || 0
    if (update.sales_share_pct !== undefined) update.sales_share_pct = Number(update.sales_share_pct) || 0

    // Re-validate against the *effective* post-update state — a partial edit
    // (e.g. only registration_share_pct) must not silently break the same
    // rate/split invariants enforced at create time.
    const effectiveRate = update.rate !== undefined ? Number(update.rate) : undefined
    if (effectiveRate !== undefined) {
      if (effectiveRate < 0) return { success: false, error: 'Rate cannot be negative' }
      const effectiveCalcType = update.calculation_type !== undefined ? String(update.calculation_type) : existing.calculation_type
      if (effectiveCalcType === 'percentage' && effectiveRate > 100) {
        return { success: false, error: 'A percentage rate cannot exceed 100' }
      }
    }
    const effectiveOwnership = update.ownership_model !== undefined ? String(update.ownership_model) : existing.ownership_model
    if (effectiveOwnership === 'split' && (update.registration_share_pct !== undefined || update.sales_share_pct !== undefined || update.ownership_model !== undefined)) {
      const effectiveReg = update.registration_share_pct !== undefined ? Number(update.registration_share_pct) : Number(existing.registration_share_pct || 0)
      const effectiveSales = update.sales_share_pct !== undefined ? Number(update.sales_share_pct) : Number(existing.sales_share_pct || 0)
      if (effectiveReg < 0 || effectiveSales < 0 || Math.round(effectiveReg + effectiveSales) !== 100) {
        return { success: false, error: 'Registration + Sales share must both be non-negative and add up to 100%' }
      }
    }

    // Snapshot the pre-update values whenever a rate/scope-affecting field
    // actually changes — commission_ledger rows already store baked-in
    // dollar amounts (never a live rule reference) so past commissions were
    // never at risk, this only makes "what was the rate on date X" auditable.
    const VERSIONED_FIELDS = ['rate', 'calculation_type', 'scope', 'product_id', 'category_id', 'brand'] as const
    const rateChanged = VERSIONED_FIELDS.some(f => update[f] !== undefined && String(update[f]) !== String((existing as Record<string, unknown>)[f] ?? ''))
    if (rateChanged) {
      const caller = authUser()
      const priorHistory = db.prepare(`
        SELECT effective_end_date FROM commission_rule_history WHERE rule_id=? ORDER BY created_at DESC LIMIT 1
      `).get(id) as { effective_end_date: string | null } | undefined
      const historyId = crypto.randomUUID()
      const historyRow = {
        id: historyId, rule_id: id, product_id: existing.product_id, scope: existing.scope,
        calculation_type: existing.calculation_type, rate: existing.rate,
        effective_start_date: priorHistory?.effective_end_date || existing.created_at,
        effective_end_date: new Date().toISOString(),
        created_by: (caller.id as string) || null,
      }
      db.prepare(`
        INSERT INTO commission_rule_history
          (id, rule_id, product_id, scope, calculation_type, rate, effective_start_date, effective_end_date, created_by)
        VALUES (@id,@rule_id,@product_id,@scope,@calculation_type,@rate,@effective_start_date,@effective_end_date,@created_by)
      `).run(historyRow)
      await enqueuSync('commission_rule_history', historyId, 'INSERT', historyRow)
    }

    const fields = Object.keys(update).map(k => `${k} = @${k}`).join(', ')
    if (fields) db.prepare(`UPDATE commission_rules SET ${fields}, updated_at=datetime('now') WHERE id=@id`).run({ ...update, id })
    await enqueuSync('commission_rules', id, 'UPDATE', { id, ...update })
    logAudit(db, {
      userId: (authUser().id as string) || null, action: 'COMMISSION_RULE_UPDATED',
      tableName: 'commission_rules', recordId: id, newValues: update,
    })
    return { success: true }
  })

  safeHandle(ipcMain, 'commissions:rules:history', (_e, ruleId: string) => {
    const perms = currentPerms()
    if (!canViewCommissions(perms)) return { success: false, error: 'Smart Buy access required' }
    const db = getDb()
    const rows = db.prepare(`
      SELECT crh.*, u.name as created_by_name
      FROM commission_rule_history crh
      LEFT JOIN users u ON u.id = crh.created_by
      WHERE crh.rule_id = ?
      ORDER BY crh.created_at DESC
    `).all(ruleId)
    return { success: true, data: rows }
  })

  safeHandle(ipcMain, 'commissions:rules:delete', async (_e, id: string) => {
    const perms = currentPerms()
    if (!isCommissionAdmin(perms)) return { success: false, error: 'Super Admin access required to delete commission rules' }
    const db = getDb()
    const existing = db.prepare('SELECT id FROM commission_rules WHERE id=?').get(id)
    if (!existing) return { success: false, error: 'Commission rule not found' }
    // Soft-disable rather than hard delete — commission_ledger rows keep a
    // rule_id FK for audit/history and must keep resolving to something.
    db.prepare(`UPDATE commission_rules SET status='inactive', updated_at=datetime('now') WHERE id=?`).run(id)
    await enqueuSync('commission_rules', id, 'UPDATE', { id, status: 'inactive' })
    logAudit(db, {
      userId: (authUser().id as string) || null, action: 'COMMISSION_RULE_DEACTIVATED',
      tableName: 'commission_rules', recordId: id,
    })
    return { success: true }
  })

  // ── Ledger ─────────────────────────────────────────────────────────────
  safeHandle(ipcMain, 'commissions:ledger:list', (_e, filters: {
    schemeId?: string; agentId?: string; branchId?: string; status?: string; dateFrom?: string; dateTo?: string
  } = {}) => {
    const db = getDb()
    const caller = authUser()
    const perms = currentPerms(caller)
    if (!canViewCommissions(perms)) return { success: false, error: 'Smart Buy access required' }
    const branchId = resolveScopedBranchId(perms, caller, filters.branchId)
    const scopedAgentId = resolveScopedAgentId(caller)

    const conditions: string[] = []
    const params: unknown[] = []
    if (branchId) { conditions.push('cl.branch_id = ?'); params.push(branchId) }
    // An Agent session only ever sees ledger lines crediting them.
    if (scopedAgentId) {
      conditions.push('(cl.registration_agent_id = ? OR cl.sales_agent_id = ?)')
      params.push(scopedAgentId, scopedAgentId)
    } else if (filters.agentId) {
      conditions.push('(cl.registration_agent_id = ? OR cl.sales_agent_id = ?)')
      params.push(filters.agentId, filters.agentId)
    }
    if (filters.schemeId) { conditions.push('cl.scheme_id = ?'); params.push(filters.schemeId) }
    if (filters.status) { conditions.push('cl.status = ?'); params.push(filters.status) }
    if (filters.dateFrom) { conditions.push('date(cl.created_at) >= date(?)'); params.push(filters.dateFrom) }
    if (filters.dateTo) { conditions.push('date(cl.created_at) <= date(?)'); params.push(filters.dateTo) }
    const where = conditions.length ? `WHERE ${conditions.join(' AND ')}` : ''

    const rows = db.prepare(`
      SELECT cl.*, cs.name as scheme_name, cs.scheme_number,
        ra.name as registration_agent_name, ra.code as registration_agent_code,
        sa.name as sales_agent_name, sa.code as sales_agent_code,
        r.name as rule_name, c.name as customer_name
      FROM commission_ledger cl
      LEFT JOIN chit_schemes cs ON cs.id = cl.scheme_id
      LEFT JOIN agents ra ON ra.id = cl.registration_agent_id
      LEFT JOIN agents sa ON sa.id = cl.sales_agent_id
      LEFT JOIN commission_rules r ON r.id = cl.rule_id
      LEFT JOIN chit_members m ON m.id = cl.member_id
      LEFT JOIN customers c ON c.id = m.customer_id
      ${where}
      ORDER BY cl.created_at DESC
    `).all(...params)
    return { success: true, data: rows }
  })

  // Status-aware: one "Approve" action serves both approval levels, routing
  // on the entry's current status rather than exposing 4 separate endpoints.
  // pending_manager_approval -> pending_admin_approval (branch-scoped Smart
  // Buy management access) -> approved_for_payment (Super Admin only).
  safeHandle(ipcMain, 'commissions:ledger:approve', async (_e, id: string, remarks?: string) => {
    const perms = currentPerms()
    const db = getDb()
    const caller = authUser()
    // An Agent-portal session must never approve/reject a commission entry
    // — not even their own — regardless of what module permissions their
    // linked login role carries. Mirrors the same self-dealing prevention
    // already applied to scheme creation and agent-profile edits elsewhere
    // in this module (SmartBuy commission-flow audit).
    if (resolveScopedAgentId(caller)) {
      return { success: false, error: 'Agents cannot approve or reject commission entries' }
    }
    const line = db.prepare(`
      SELECT id, status, branch_id, registration_agent_id, sales_agent_id FROM commission_ledger WHERE id=?
    `).get(id) as { id: string; status: string; branch_id: unknown; registration_agent_id: string | null; sales_agent_id: string | null } | undefined
    if (!line) return { success: false, error: 'Commission ledger entry not found' }
    const agentId = line.registration_agent_id || line.sales_agent_id || null

    if (line.status === 'pending_manager_approval') {
      if (!canViewCommissions(perms)) return { success: false, error: 'Smart Buy management access required' }
      if (!assertCommissionBranchScope(perms, caller, line.branch_id)) {
        return { success: false, error: 'You do not have access to this commission entry' }
      }
      db.prepare(`UPDATE commission_ledger SET status='pending_admin_approval', approved_by=?, approved_at=datetime('now'), updated_at=datetime('now') WHERE id=?`)
        .run(caller.id || null, id)
      await enqueuSync('commission_ledger', id, 'UPDATE', { id, status: 'pending_admin_approval', approved_by: caller.id || null })
      await writeApprovalLog(db, {
        commissionId: id, agentId, branchId: line.branch_id, action: 'MANAGER_APPROVED',
        previousStatus: line.status, newStatus: 'pending_admin_approval', changedBy: (caller.id as string) || null, remarks,
      })
      logAudit(db, {
        userId: (caller.id as string) || null, branchId: (line.branch_id as string) || null,
        action: 'COMMISSION_MANAGER_APPROVED', tableName: 'commission_ledger', recordId: id,
        oldValues: { status: line.status }, newValues: { status: 'pending_admin_approval', remarks },
      })
      createNotification('commission_pending_admin', 'Commission Approval Request',
        'A SmartBuy Manager approved a commission entry — it now needs your final approval.',
        { commissionId: id }, { roleScope: 'owner' })
      return { success: true }
    }

    if (line.status === 'pending_admin_approval') {
      if (!isCommissionAdmin(perms)) return { success: false, error: 'Super Admin access required for final approval' }
      db.prepare(`UPDATE commission_ledger SET status='approved_for_payment', admin_approved_by=?, admin_approved_at=datetime('now'), updated_at=datetime('now') WHERE id=?`)
        .run(caller.id || null, id)
      await enqueuSync('commission_ledger', id, 'UPDATE', { id, status: 'approved_for_payment', admin_approved_by: caller.id || null })
      await writeApprovalLog(db, {
        commissionId: id, agentId, branchId: line.branch_id, action: 'ADMIN_APPROVED',
        previousStatus: line.status, newStatus: 'approved_for_payment', changedBy: (caller.id as string) || null, remarks,
      })
      logAudit(db, {
        userId: (caller.id as string) || null, branchId: (line.branch_id as string) || null,
        action: 'COMMISSION_ADMIN_APPROVED', tableName: 'commission_ledger', recordId: id,
        oldValues: { status: line.status }, newValues: { status: 'approved_for_payment', remarks },
      })
      notifyAgentUser(db, agentId, 'commission_approved', 'Commission Approved',
        'Your commission entry was approved and is ready for payment.', { commissionId: id })
      return { success: true }
    }

    return { success: false, error: `This commission entry is ${line.status.replace(/_/g, ' ')} — not awaiting approval` }
  })

  // Same dual-level routing as approve, but to a terminal 'rejected' state —
  // a reason is mandatory since there's no reversal flow for a rejection.
  safeHandle(ipcMain, 'commissions:ledger:reject', async (_e, id: string, remarks: string) => {
    if (!remarks || !remarks.trim()) return { success: false, error: 'A reason is required to reject a commission entry' }
    const perms = currentPerms()
    const db = getDb()
    const caller = authUser()
    if (resolveScopedAgentId(caller)) {
      return { success: false, error: 'Agents cannot approve or reject commission entries' }
    }
    const line = db.prepare(`
      SELECT id, status, branch_id, registration_agent_id, sales_agent_id FROM commission_ledger WHERE id=?
    `).get(id) as { id: string; status: string; branch_id: unknown; registration_agent_id: string | null; sales_agent_id: string | null } | undefined
    if (!line) return { success: false, error: 'Commission ledger entry not found' }
    const agentId = line.registration_agent_id || line.sales_agent_id || null

    let action: string
    if (line.status === 'pending_manager_approval') {
      if (!canViewCommissions(perms)) return { success: false, error: 'Smart Buy management access required' }
      if (!assertCommissionBranchScope(perms, caller, line.branch_id)) {
        return { success: false, error: 'You do not have access to this commission entry' }
      }
      action = 'MANAGER_REJECTED'
    } else if (line.status === 'pending_admin_approval') {
      if (!isCommissionAdmin(perms)) return { success: false, error: 'Super Admin access required to reject at this stage' }
      action = 'ADMIN_REJECTED'
    } else {
      return { success: false, error: `This commission entry is ${line.status.replace(/_/g, ' ')} — not awaiting approval` }
    }

    db.prepare(`UPDATE commission_ledger SET status='rejected', updated_at=datetime('now') WHERE id=?`).run(id)
    await enqueuSync('commission_ledger', id, 'UPDATE', { id, status: 'rejected' })
    await writeApprovalLog(db, {
      commissionId: id, agentId, branchId: line.branch_id, action,
      previousStatus: line.status, newStatus: 'rejected', changedBy: (caller.id as string) || null, remarks,
    })
    logAudit(db, {
      userId: (caller.id as string) || null, branchId: (line.branch_id as string) || null,
      action: 'COMMISSION_REJECTED', tableName: 'commission_ledger', recordId: id,
      oldValues: { status: line.status }, newValues: { status: 'rejected', remarks },
    })
    notifyAgentUser(db, agentId, 'commission_rejected', 'Commission Rejected',
      `Your commission entry was rejected: ${remarks}`, { commissionId: id })
    return { success: true }
  })

  // Cancellation is a manual Super Admin action only (e.g. a data-entry
  // mistake) — no automatic link to scheme cancellation.
  safeHandle(ipcMain, 'commissions:ledger:cancel', async (_e, id: string, remarks?: string) => {
    const perms = currentPerms()
    if (!isCommissionAdmin(perms)) return { success: false, error: 'Super Admin access required to cancel a commission entry' }
    const db = getDb()
    const caller = authUser()
    const line = db.prepare(`
      SELECT id, status, branch_id, registration_agent_id, sales_agent_id FROM commission_ledger WHERE id=?
    `).get(id) as { id: string; status: string; branch_id: unknown; registration_agent_id: string | null; sales_agent_id: string | null } | undefined
    if (!line) return { success: false, error: 'Commission ledger entry not found' }
    if (['paid', 'rejected', 'cancelled'].includes(line.status)) {
      return { success: false, error: `Cannot cancel a ${line.status} commission entry` }
    }
    const agentId = line.registration_agent_id || line.sales_agent_id || null

    db.prepare(`UPDATE commission_ledger SET status='cancelled', updated_at=datetime('now') WHERE id=?`).run(id)
    await enqueuSync('commission_ledger', id, 'UPDATE', { id, status: 'cancelled' })
    await writeApprovalLog(db, {
      commissionId: id, agentId, branchId: line.branch_id, action: 'CANCELLED',
      previousStatus: line.status, newStatus: 'cancelled', changedBy: (caller.id as string) || null, remarks,
    })
    logAudit(db, {
      userId: (caller.id as string) || null, branchId: (line.branch_id as string) || null,
      action: 'COMMISSION_CANCELLED', tableName: 'commission_ledger', recordId: id,
      oldValues: { status: line.status }, newValues: { status: 'cancelled', remarks },
    })
    return { success: true }
  })

  // Marking paid is a Super-Admin-only financial action (distinct from
  // approval). Kept as a single-row convenience path alongside the batch
  // commissions:payouts:create — both now require 'approved_for_payment'.
  safeHandle(ipcMain, 'commissions:ledger:markPaid', async (_e, ids: string[]) => {
    const perms = currentPerms()
    if (!isCommissionAdmin(perms)) return { success: false, error: 'Super Admin access required to mark commission as paid' }
    const db = getDb()
    const caller = authUser()
    const list = Array.isArray(ids) ? ids : [ids]
    let updated = 0
    for (const id of list) {
      const line = db.prepare(`
        SELECT id, status, branch_id, registration_agent_id, sales_agent_id FROM commission_ledger WHERE id=?
      `).get(id) as { id: string; status: string; branch_id: unknown; registration_agent_id: string | null; sales_agent_id: string | null } | undefined
      if (!line || line.status !== 'approved_for_payment') continue
      db.prepare(`UPDATE commission_ledger SET status='paid', paid_at=datetime('now'), updated_at=datetime('now') WHERE id=?`).run(id)
      await enqueuSync('commission_ledger', id, 'UPDATE', { id, status: 'paid' })
      const paidAgentId = line.registration_agent_id || line.sales_agent_id || null
      await writeApprovalLog(db, {
        commissionId: id, agentId: paidAgentId, branchId: line.branch_id,
        action: 'PAID', previousStatus: line.status, newStatus: 'paid', changedBy: (caller.id as string) || null,
      })
      logAudit(db, {
        userId: (caller.id as string) || null, branchId: (line.branch_id as string) || null, action: 'COMMISSION_PAID',
        tableName: 'commission_ledger', recordId: id, oldValues: { status: line.status }, newValues: { status: 'paid' },
      })
      notifyAgentUser(db, paidAgentId, 'commission_paid', 'Commission Paid',
        'Your commission entry has been paid.', { commissionId: id })
      updated++
    }
    return { success: true, data: { updated } }
  })

  // Per-entry approval history — the "Generated by System / Approved by
  // Manager / Approved by Admin" timeline the UI shows against one
  // commission line. Same branch/agent scoping as commissions:ledger:list.
  safeHandle(ipcMain, 'commissions:approvalLogs:list', (_e, commissionId: string) => {
    const perms = currentPerms()
    if (!canViewCommissions(perms)) return { success: false, error: 'Smart Buy access required' }
    const db = getDb()
    const caller = authUser()
    const line = db.prepare('SELECT id, branch_id, registration_agent_id, sales_agent_id FROM commission_ledger WHERE id=?')
      .get(commissionId) as { id: string; branch_id: unknown; registration_agent_id: string | null; sales_agent_id: string | null } | undefined
    if (!line) return { success: false, error: 'Commission ledger entry not found' }
    if (!assertCommissionBranchScope(perms, caller, line.branch_id)) {
      return { success: false, error: 'You do not have access to this commission entry' }
    }
    const scopedAgentId = resolveScopedAgentId(caller)
    if (scopedAgentId && line.registration_agent_id !== scopedAgentId && line.sales_agent_id !== scopedAgentId) {
      return { success: false, error: 'You do not have access to this commission entry' }
    }
    const rows = db.prepare(`
      SELECT cal.*, u.name as changed_by_name
      FROM commission_approval_logs cal
      LEFT JOIN users u ON u.id = cal.changed_by
      WHERE cal.commission_id = ?
      ORDER BY cal.created_at ASC
    `).all(commissionId)
    return { success: true, data: rows }
  })

  // Records one real payment event to one agent, covering one or more
  // approved ledger entries in a single batch — gives "Paid Commission" a
  // real amount/method/reference/paid-by trail instead of a bare status
  // flag. Every covered entry must already be credited to this agent
  // (registration or sales side) and 'approved' — same precondition
  // markPaid enforces per-row, just validated up front for the whole batch.
  safeHandle(ipcMain, 'commissions:payouts:create', async (_e, payload: {
    agentId?: string; ledgerIds?: string[]; method?: string; reference?: string; notes?: string
  } = {}) => {
    const perms = currentPerms()
    if (!isCommissionAdmin(perms)) return { success: false, error: 'Super Admin access required to record a commission payout' }
    const db = getDb()
    const caller = authUser()
    const agentId = String(payload.agentId || '')
    const ledgerIds = Array.isArray(payload.ledgerIds) ? [...new Set(payload.ledgerIds.filter(Boolean).map(String))] : []
    if (!agentId) return { success: false, error: 'Select an agent' }
    if (ledgerIds.length === 0) return { success: false, error: 'Select at least one approved commission entry to pay' }

    const agent = db.prepare('SELECT id, name, code, branch_id FROM agents WHERE id=?').get(agentId) as { id: string; name: string; code: string; branch_id: unknown } | undefined
    if (!agent) return { success: false, error: 'Agent not found' }

    const placeholders = ledgerIds.map(() => '?').join(',')
    const lines = db.prepare(`
      SELECT id, status, total_commission, registration_agent_id, sales_agent_id, branch_id
      FROM commission_ledger WHERE id IN (${placeholders})
    `).all(...ledgerIds) as Array<{
      id: string; status: string; total_commission: number
      registration_agent_id: string | null; sales_agent_id: string | null; branch_id: unknown
    }>
    if (lines.length !== ledgerIds.length) return { success: false, error: 'One or more commission entries were not found' }
    const invalid = lines.find(l => l.status !== 'approved_for_payment' || (l.registration_agent_id !== agentId && l.sales_agent_id !== agentId))
    if (invalid) return { success: false, error: 'Every selected entry must be approved for payment and credited to this agent' }

    const amount = money(lines.reduce((sum, l) => sum + (Number(l.total_commission) || 0), 0))
    const payoutId = crypto.randomUUID()
    const branchId = agent.branch_id || lines[0]?.branch_id || null
    const row = {
      id: payoutId, agent_id: agentId, branch_id: branchId, amount,
      method: String(payload.method || 'cash'), reference: payload.reference || null,
      paid_by: caller.id || null, notes: payload.notes || null,
    }

    db.transaction(() => {
      db.prepare(`
        INSERT INTO commission_payouts (id, agent_id, branch_id, amount, method, reference, paid_by, notes)
        VALUES (@id,@agent_id,@branch_id,@amount,@method,@reference,@paid_by,@notes)
      `).run(row)
      for (const l of lines) {
        db.prepare(`UPDATE commission_ledger SET status='paid', paid_at=datetime('now'), payout_id=?, updated_at=datetime('now') WHERE id=?`)
          .run(payoutId, l.id)
      }
    })()

    await enqueuSync('commission_payouts', payoutId, 'INSERT', row)
    for (const l of lines) {
      await enqueuSync('commission_ledger', l.id, 'UPDATE', { id: l.id, status: 'paid', payout_id: payoutId })
      await writeApprovalLog(db, {
        commissionId: l.id, agentId, branchId: l.branch_id, action: 'PAID',
        previousStatus: l.status, newStatus: 'paid', changedBy: (caller.id as string) || null,
        remarks: payload.notes,
      })
    }
    logAudit(db, {
      userId: (caller.id as string) || null, branchId: (branchId as string) || null,
      action: 'COMMISSION_PAYOUT_RECORDED', tableName: 'commission_payouts', recordId: payoutId,
      oldValues: { ledgerIds, previousStatus: 'approved_for_payment' },
      newValues: { agentId, amount, ledgerCount: lines.length },
    })
    notifyAgentUser(db, agentId, 'commission_paid', 'Commission Paid',
      `A payout of Rs.${amount} covering ${lines.length} commission entr${lines.length === 1 ? 'y' : 'ies'} has been paid.`,
      { payoutId, amount })
    if (amount >= largePayoutThreshold()) {
      createNotification('commission_large_payout', 'Large Commission Payout',
        `A payout of Rs.${amount} was recorded for ${agent.name} (${agent.code}).`,
        { payoutId, agentId, amount }, { roleScope: 'owner' })
    }
    return { success: true, data: { id: payoutId, amount } }
  })

  safeHandle(ipcMain, 'commissions:payouts:list', (_e, filters: { agentId?: string; branchId?: string } = {}) => {
    const perms = currentPerms()
    if (!canViewCommissions(perms)) return { success: false, error: 'Smart Buy access required' }
    const db = getDb()
    const caller = authUser()
    const branchId = resolveScopedBranchId(perms, caller, filters.branchId)
    const scopedAgentId = resolveScopedAgentId(caller)

    const conditions: string[] = []
    const params: unknown[] = []
    if (branchId) { conditions.push('cp.branch_id = ?'); params.push(branchId) }
    if (scopedAgentId) {
      conditions.push('cp.agent_id = ?'); params.push(scopedAgentId)
    } else if (filters.agentId) {
      conditions.push('cp.agent_id = ?'); params.push(filters.agentId)
    }
    const where = conditions.length ? `WHERE ${conditions.join(' AND ')}` : ''
    const rows = db.prepare(`
      SELECT cp.*, a.name as agent_name, a.code as agent_code, u.name as paid_by_name,
        (SELECT COUNT(*) FROM commission_ledger cl WHERE cl.payout_id = cp.id) as entries_count
      FROM commission_payouts cp
      LEFT JOIN agents a ON a.id = cp.agent_id
      LEFT JOIN users u ON u.id = cp.paid_by
      ${where}
      ORDER BY cp.paid_at DESC
    `).all(...params)
    return { success: true, data: rows }
  })

  // ── Agent Commission Statement ────────────────────────────────────────
  // A commission_ledger row comes from exactly one of two sale events —
  // a POS retail line (source_table='invoice_items', product via
  // invoice_items->products, customer via invoices->customers) or a
  // SmartBuy redemption (source_table='chit_members', product/customer via
  // the member row directly, since redemption always writes them there).
  // Two matching-shape SELECTs UNION ALL'd rather than one query with
  // conditional joins — clearer than threading a source_table CASE through
  // every join condition.
  safeHandle(ipcMain, 'commissions:statement:generate', (_e, agentId: string, filters: {
    dateFrom?: string; dateTo?: string; month?: number; year?: number; status?: string
  } = {}) => {
    const perms = currentPerms()
    if (!canViewCommissions(perms)) return { success: false, error: 'Smart Buy access required' }
    const db = getDb()
    const caller = authUser()
    const scopedAgentId = resolveScopedAgentId(caller)
    if (scopedAgentId && scopedAgentId !== agentId) {
      return { success: false, error: 'You do not have access to this agent' }
    }

    const agent = db.prepare(`
      SELECT a.id, a.name, a.code, a.branch_id, b.name as branch_name, mgr.name as smartbuy_manager_name
      FROM agents a
      LEFT JOIN branches b ON b.id = a.branch_id
      LEFT JOIN users mgr ON mgr.id = b.smartbuy_manager_id
      WHERE a.id = ?
    `).get(agentId) as Record<string, unknown> | undefined
    if (!agent) return { success: false, error: 'Agent not found' }
    if (!assertCommissionBranchScope(perms, caller, agent.branch_id)) {
      return { success: false, error: 'You do not have access to this agent' }
    }

    let dateFrom = filters.dateFrom
    let dateTo = filters.dateTo
    if (!dateFrom && !dateTo && filters.year) {
      const month = filters.month ? String(filters.month).padStart(2, '0') : null
      dateFrom = month ? `${filters.year}-${month}-01` : `${filters.year}-01-01`
      dateTo = month ? `${filters.year}-${month}-31` : `${filters.year}-12-31`
    }

    const dateConditions: string[] = []
    const dateParams: unknown[] = []
    if (dateFrom) { dateConditions.push('date(cl.created_at) >= date(?)'); dateParams.push(dateFrom) }
    if (dateTo) { dateConditions.push('date(cl.created_at) <= date(?)'); dateParams.push(dateTo) }
    const dateWhere = dateConditions.length ? ` AND ${dateConditions.join(' AND ')}` : ''

    const summary = db.prepare(`
      SELECT
        COUNT(*) as total_products_sold,
        COUNT(DISTINCT CASE WHEN cl.source_table='chit_members' THEN cl.scheme_id END) as total_schemes,
        COALESCE(SUM(cl.base_amount), 0) as total_sales,
        COALESCE(SUM(cl.total_commission), 0) as commission_generated,
        COALESCE(SUM(CASE WHEN cl.status='approved_for_payment' THEN cl.total_commission ELSE 0 END), 0) as commission_approved,
        COALESCE(SUM(CASE WHEN cl.status='paid' THEN cl.total_commission ELSE 0 END), 0) as commission_paid,
        COALESCE(SUM(CASE WHEN cl.status IN ('pending_manager_approval','pending_admin_approval') THEN cl.total_commission ELSE 0 END), 0) as commission_pending
      FROM commission_ledger cl
      WHERE (cl.registration_agent_id = ? OR cl.sales_agent_id = ?)${dateWhere}
    `).get(agentId, agentId, ...dateParams)

    const statusWhere = filters.status ? ' AND cl.status = ?' : ''
    const statusParams = filters.status ? [filters.status] : []
    const transactions = db.prepare(`
      SELECT * FROM (
        SELECT cl.id, cl.created_at as date, p.name as product, NULL as scheme_name,
          cust.name as customer_name, cl.base_amount as sales_amount, cl.total_commission as commission_amount, cl.status
        FROM commission_ledger cl
        LEFT JOIN invoice_items ii ON ii.id = cl.source_id
        LEFT JOIN invoices inv ON inv.id = ii.invoice_id
        LEFT JOIN products p ON p.id = ii.product_id
        LEFT JOIN customers cust ON cust.id = inv.customer_id
        WHERE cl.source_table = 'invoice_items' AND (cl.registration_agent_id = ? OR cl.sales_agent_id = ?)${dateWhere}${statusWhere}
        UNION ALL
        SELECT cl.id, cl.created_at as date, p.name as product, cs.name as scheme_name,
          cust.name as customer_name, cl.base_amount as sales_amount, cl.total_commission as commission_amount, cl.status
        FROM commission_ledger cl
        LEFT JOIN chit_members m ON m.id = cl.member_id
        LEFT JOIN chit_schemes cs ON cs.id = m.scheme_id
        LEFT JOIN products p ON p.id = m.redeemed_product_id
        LEFT JOIN customers cust ON cust.id = m.customer_id
        WHERE cl.source_table = 'chit_members' AND (cl.registration_agent_id = ? OR cl.sales_agent_id = ?)${dateWhere}${statusWhere}
      )
      ORDER BY date DESC
    `).all(agentId, agentId, ...dateParams, ...statusParams, agentId, agentId, ...dateParams, ...statusParams)

    db.prepare(`
      INSERT INTO commission_statement_history (id, agent_id, generated_by, period_from, period_to, status_filter)
      VALUES (?, ?, ?, ?, ?, ?)
    `).run(crypto.randomUUID(), agentId, caller.id || null, dateFrom || null, dateTo || null, filters.status || null)

    return { success: true, data: { agent, summary, transactions } }
  })
}
